// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBBaqmybxqA3Ak9BzLnsEubAuGBn_vrp8',
    appId: '1:1055393658402:web:401934657b102459003c7b',
    messagingSenderId: '1055393658402',
    projectId: 'csen268-f25',
    authDomain: 'csen268-f25.firebaseapp.com',
    storageBucket: 'csen268-f25.firebasestorage.app',
    measurementId: 'G-EJGFTXNNDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6Fp-A9aqZ4u24cQ5VDcL_2_ruILiZIw',
    appId: '1:1055393658402:android:d2a93d55916b5533003c7b',
    messagingSenderId: '1055393658402',
    projectId: 'csen268-f25',
    storageBucket: 'csen268-f25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeGwnXoARQi1XQ_FPfz7p4kUNoidfB5Wc',
    appId: '1:1055393658402:ios:d9b37d4e78539ab2003c7b',
    messagingSenderId: '1055393658402',
    projectId: 'csen268-f25',
    storageBucket: 'csen268-f25.firebasestorage.app',
    iosBundleId: 'com.artun.csen268',
  );
}
